{
  try {
    request.getParams();
    Assert.fail("Expected exception");
  }
 catch (  Exception e) {
    assertTrue("Expected exception message to contain: " + errorContains,e.getMessage().contains(errorContains));
  }
}
