{
  try {
    assertBlockU(msg,"1");
    fail("expecting fail");
  }
 catch (  Exception e) {
  }
}
