{
  try {
    execBenchmark(altAlg(false));
    assertFalse("Should have failed to run the algorithm",true);
  }
 catch (  Exception e) {
  }
}
