{
  for (  Future<T> future : list) {
    try {
      func.apply(future.get());
    }
 catch (    ExecutionException e) {
      final Throwable throwable=e.getCause();
      if (throwable instanceof IOException)       throw (IOException)e.getCause();
      throw new RuntimeException(throwable);
    }
catch (    InterruptedException ie) {
      throw new ThreadInterruptedException(ie);
    }
  }
}
