{
  if (doFail && name.equals("rollback before checkpoint"))   throw new RuntimeException("intentionally failing");
}
